// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module clu_single_lin_process_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_lin_addr_AWVALID,
        m_axi_lin_addr_AWREADY,
        m_axi_lin_addr_AWADDR,
        m_axi_lin_addr_AWID,
        m_axi_lin_addr_AWLEN,
        m_axi_lin_addr_AWSIZE,
        m_axi_lin_addr_AWBURST,
        m_axi_lin_addr_AWLOCK,
        m_axi_lin_addr_AWCACHE,
        m_axi_lin_addr_AWPROT,
        m_axi_lin_addr_AWQOS,
        m_axi_lin_addr_AWREGION,
        m_axi_lin_addr_AWUSER,
        m_axi_lin_addr_WVALID,
        m_axi_lin_addr_WREADY,
        m_axi_lin_addr_WDATA,
        m_axi_lin_addr_WSTRB,
        m_axi_lin_addr_WLAST,
        m_axi_lin_addr_WID,
        m_axi_lin_addr_WUSER,
        m_axi_lin_addr_ARVALID,
        m_axi_lin_addr_ARREADY,
        m_axi_lin_addr_ARADDR,
        m_axi_lin_addr_ARID,
        m_axi_lin_addr_ARLEN,
        m_axi_lin_addr_ARSIZE,
        m_axi_lin_addr_ARBURST,
        m_axi_lin_addr_ARLOCK,
        m_axi_lin_addr_ARCACHE,
        m_axi_lin_addr_ARPROT,
        m_axi_lin_addr_ARQOS,
        m_axi_lin_addr_ARREGION,
        m_axi_lin_addr_ARUSER,
        m_axi_lin_addr_RVALID,
        m_axi_lin_addr_RREADY,
        m_axi_lin_addr_RDATA,
        m_axi_lin_addr_RLAST,
        m_axi_lin_addr_RID,
        m_axi_lin_addr_RFIFONUM,
        m_axi_lin_addr_RUSER,
        m_axi_lin_addr_RRESP,
        m_axi_lin_addr_BVALID,
        m_axi_lin_addr_BREADY,
        m_axi_lin_addr_BRESP,
        m_axi_lin_addr_BID,
        m_axi_lin_addr_BUSER,
        linbase,
        m_axi_ps_ddr_AWVALID,
        m_axi_ps_ddr_AWREADY,
        m_axi_ps_ddr_AWADDR,
        m_axi_ps_ddr_AWID,
        m_axi_ps_ddr_AWLEN,
        m_axi_ps_ddr_AWSIZE,
        m_axi_ps_ddr_AWBURST,
        m_axi_ps_ddr_AWLOCK,
        m_axi_ps_ddr_AWCACHE,
        m_axi_ps_ddr_AWPROT,
        m_axi_ps_ddr_AWQOS,
        m_axi_ps_ddr_AWREGION,
        m_axi_ps_ddr_AWUSER,
        m_axi_ps_ddr_WVALID,
        m_axi_ps_ddr_WREADY,
        m_axi_ps_ddr_WDATA,
        m_axi_ps_ddr_WSTRB,
        m_axi_ps_ddr_WLAST,
        m_axi_ps_ddr_WID,
        m_axi_ps_ddr_WUSER,
        m_axi_ps_ddr_ARVALID,
        m_axi_ps_ddr_ARREADY,
        m_axi_ps_ddr_ARADDR,
        m_axi_ps_ddr_ARID,
        m_axi_ps_ddr_ARLEN,
        m_axi_ps_ddr_ARSIZE,
        m_axi_ps_ddr_ARBURST,
        m_axi_ps_ddr_ARLOCK,
        m_axi_ps_ddr_ARCACHE,
        m_axi_ps_ddr_ARPROT,
        m_axi_ps_ddr_ARQOS,
        m_axi_ps_ddr_ARREGION,
        m_axi_ps_ddr_ARUSER,
        m_axi_ps_ddr_RVALID,
        m_axi_ps_ddr_RREADY,
        m_axi_ps_ddr_RDATA,
        m_axi_ps_ddr_RLAST,
        m_axi_ps_ddr_RID,
        m_axi_ps_ddr_RFIFONUM,
        m_axi_ps_ddr_RUSER,
        m_axi_ps_ddr_RRESP,
        m_axi_ps_ddr_BVALID,
        m_axi_ps_ddr_BREADY,
        m_axi_ps_ddr_BRESP,
        m_axi_ps_ddr_BID,
        m_axi_ps_ddr_BUSER,
        ddr,
        timestamp,
        EN,
        received_lin,
        received_lin_ap_vld
);

parameter    ap_ST_fsm_state1 = 44'd1;
parameter    ap_ST_fsm_state2 = 44'd2;
parameter    ap_ST_fsm_state3 = 44'd4;
parameter    ap_ST_fsm_state4 = 44'd8;
parameter    ap_ST_fsm_state5 = 44'd16;
parameter    ap_ST_fsm_state6 = 44'd32;
parameter    ap_ST_fsm_state7 = 44'd64;
parameter    ap_ST_fsm_state8 = 44'd128;
parameter    ap_ST_fsm_state9 = 44'd256;
parameter    ap_ST_fsm_state10 = 44'd512;
parameter    ap_ST_fsm_state11 = 44'd1024;
parameter    ap_ST_fsm_state12 = 44'd2048;
parameter    ap_ST_fsm_state13 = 44'd4096;
parameter    ap_ST_fsm_state14 = 44'd8192;
parameter    ap_ST_fsm_state15 = 44'd16384;
parameter    ap_ST_fsm_state16 = 44'd32768;
parameter    ap_ST_fsm_state17 = 44'd65536;
parameter    ap_ST_fsm_state18 = 44'd131072;
parameter    ap_ST_fsm_state19 = 44'd262144;
parameter    ap_ST_fsm_state20 = 44'd524288;
parameter    ap_ST_fsm_state21 = 44'd1048576;
parameter    ap_ST_fsm_state22 = 44'd2097152;
parameter    ap_ST_fsm_state23 = 44'd4194304;
parameter    ap_ST_fsm_state24 = 44'd8388608;
parameter    ap_ST_fsm_state25 = 44'd16777216;
parameter    ap_ST_fsm_state26 = 44'd33554432;
parameter    ap_ST_fsm_state27 = 44'd67108864;
parameter    ap_ST_fsm_state28 = 44'd134217728;
parameter    ap_ST_fsm_state29 = 44'd268435456;
parameter    ap_ST_fsm_state30 = 44'd536870912;
parameter    ap_ST_fsm_state31 = 44'd1073741824;
parameter    ap_ST_fsm_state32 = 44'd2147483648;
parameter    ap_ST_fsm_state33 = 44'd4294967296;
parameter    ap_ST_fsm_state34 = 44'd8589934592;
parameter    ap_ST_fsm_state35 = 44'd17179869184;
parameter    ap_ST_fsm_state36 = 44'd34359738368;
parameter    ap_ST_fsm_state37 = 44'd68719476736;
parameter    ap_ST_fsm_state38 = 44'd137438953472;
parameter    ap_ST_fsm_state39 = 44'd274877906944;
parameter    ap_ST_fsm_state40 = 44'd549755813888;
parameter    ap_ST_fsm_state41 = 44'd1099511627776;
parameter    ap_ST_fsm_state42 = 44'd2199023255552;
parameter    ap_ST_fsm_state43 = 44'd4398046511104;
parameter    ap_ST_fsm_state44 = 44'd8796093022208;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_lin_addr_AWVALID;
input   m_axi_lin_addr_AWREADY;
output  [31:0] m_axi_lin_addr_AWADDR;
output  [0:0] m_axi_lin_addr_AWID;
output  [31:0] m_axi_lin_addr_AWLEN;
output  [2:0] m_axi_lin_addr_AWSIZE;
output  [1:0] m_axi_lin_addr_AWBURST;
output  [1:0] m_axi_lin_addr_AWLOCK;
output  [3:0] m_axi_lin_addr_AWCACHE;
output  [2:0] m_axi_lin_addr_AWPROT;
output  [3:0] m_axi_lin_addr_AWQOS;
output  [3:0] m_axi_lin_addr_AWREGION;
output  [0:0] m_axi_lin_addr_AWUSER;
output   m_axi_lin_addr_WVALID;
input   m_axi_lin_addr_WREADY;
output  [31:0] m_axi_lin_addr_WDATA;
output  [3:0] m_axi_lin_addr_WSTRB;
output   m_axi_lin_addr_WLAST;
output  [0:0] m_axi_lin_addr_WID;
output  [0:0] m_axi_lin_addr_WUSER;
output   m_axi_lin_addr_ARVALID;
input   m_axi_lin_addr_ARREADY;
output  [31:0] m_axi_lin_addr_ARADDR;
output  [0:0] m_axi_lin_addr_ARID;
output  [31:0] m_axi_lin_addr_ARLEN;
output  [2:0] m_axi_lin_addr_ARSIZE;
output  [1:0] m_axi_lin_addr_ARBURST;
output  [1:0] m_axi_lin_addr_ARLOCK;
output  [3:0] m_axi_lin_addr_ARCACHE;
output  [2:0] m_axi_lin_addr_ARPROT;
output  [3:0] m_axi_lin_addr_ARQOS;
output  [3:0] m_axi_lin_addr_ARREGION;
output  [0:0] m_axi_lin_addr_ARUSER;
input   m_axi_lin_addr_RVALID;
output   m_axi_lin_addr_RREADY;
input  [31:0] m_axi_lin_addr_RDATA;
input   m_axi_lin_addr_RLAST;
input  [0:0] m_axi_lin_addr_RID;
input  [8:0] m_axi_lin_addr_RFIFONUM;
input  [0:0] m_axi_lin_addr_RUSER;
input  [1:0] m_axi_lin_addr_RRESP;
input   m_axi_lin_addr_BVALID;
output   m_axi_lin_addr_BREADY;
input  [1:0] m_axi_lin_addr_BRESP;
input  [0:0] m_axi_lin_addr_BID;
input  [0:0] m_axi_lin_addr_BUSER;
input  [31:0] linbase;
output   m_axi_ps_ddr_AWVALID;
input   m_axi_ps_ddr_AWREADY;
output  [31:0] m_axi_ps_ddr_AWADDR;
output  [0:0] m_axi_ps_ddr_AWID;
output  [31:0] m_axi_ps_ddr_AWLEN;
output  [2:0] m_axi_ps_ddr_AWSIZE;
output  [1:0] m_axi_ps_ddr_AWBURST;
output  [1:0] m_axi_ps_ddr_AWLOCK;
output  [3:0] m_axi_ps_ddr_AWCACHE;
output  [2:0] m_axi_ps_ddr_AWPROT;
output  [3:0] m_axi_ps_ddr_AWQOS;
output  [3:0] m_axi_ps_ddr_AWREGION;
output  [0:0] m_axi_ps_ddr_AWUSER;
output   m_axi_ps_ddr_WVALID;
input   m_axi_ps_ddr_WREADY;
output  [7:0] m_axi_ps_ddr_WDATA;
output  [0:0] m_axi_ps_ddr_WSTRB;
output   m_axi_ps_ddr_WLAST;
output  [0:0] m_axi_ps_ddr_WID;
output  [0:0] m_axi_ps_ddr_WUSER;
output   m_axi_ps_ddr_ARVALID;
input   m_axi_ps_ddr_ARREADY;
output  [31:0] m_axi_ps_ddr_ARADDR;
output  [0:0] m_axi_ps_ddr_ARID;
output  [31:0] m_axi_ps_ddr_ARLEN;
output  [2:0] m_axi_ps_ddr_ARSIZE;
output  [1:0] m_axi_ps_ddr_ARBURST;
output  [1:0] m_axi_ps_ddr_ARLOCK;
output  [3:0] m_axi_ps_ddr_ARCACHE;
output  [2:0] m_axi_ps_ddr_ARPROT;
output  [3:0] m_axi_ps_ddr_ARQOS;
output  [3:0] m_axi_ps_ddr_ARREGION;
output  [0:0] m_axi_ps_ddr_ARUSER;
input   m_axi_ps_ddr_RVALID;
output   m_axi_ps_ddr_RREADY;
input  [7:0] m_axi_ps_ddr_RDATA;
input   m_axi_ps_ddr_RLAST;
input  [0:0] m_axi_ps_ddr_RID;
input  [10:0] m_axi_ps_ddr_RFIFONUM;
input  [0:0] m_axi_ps_ddr_RUSER;
input  [1:0] m_axi_ps_ddr_RRESP;
input   m_axi_ps_ddr_BVALID;
output   m_axi_ps_ddr_BREADY;
input  [1:0] m_axi_ps_ddr_BRESP;
input  [0:0] m_axi_ps_ddr_BID;
input  [0:0] m_axi_ps_ddr_BUSER;
input  [31:0] ddr;
input  [63:0] timestamp;
input  [3:0] EN;
output  [31:0] received_lin;
output   received_lin_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg m_axi_lin_addr_AWVALID;
reg[31:0] m_axi_lin_addr_AWADDR;
reg m_axi_lin_addr_WVALID;
reg[31:0] m_axi_lin_addr_WDATA;
reg m_axi_lin_addr_ARVALID;
reg[31:0] m_axi_lin_addr_ARADDR;
reg[0:0] m_axi_lin_addr_ARID;
reg[31:0] m_axi_lin_addr_ARLEN;
reg[2:0] m_axi_lin_addr_ARSIZE;
reg[1:0] m_axi_lin_addr_ARBURST;
reg[1:0] m_axi_lin_addr_ARLOCK;
reg[3:0] m_axi_lin_addr_ARCACHE;
reg[2:0] m_axi_lin_addr_ARPROT;
reg[3:0] m_axi_lin_addr_ARQOS;
reg[3:0] m_axi_lin_addr_ARREGION;
reg[0:0] m_axi_lin_addr_ARUSER;
reg m_axi_lin_addr_RREADY;
reg m_axi_lin_addr_BREADY;
reg m_axi_ps_ddr_AWVALID;
reg m_axi_ps_ddr_WVALID;
reg m_axi_ps_ddr_ARVALID;
reg m_axi_ps_ddr_RREADY;
reg m_axi_ps_ddr_BREADY;
reg received_lin_ap_vld;

(* fsm_encoding = "none" *) reg   [43:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [3:0] PLIN_Ctrl_run_state_address0;
reg    PLIN_Ctrl_run_state_ce0;
reg    PLIN_Ctrl_run_state_we0;
reg   [0:0] PLIN_Ctrl_run_state_d0;
wire   [0:0] PLIN_Ctrl_run_state_q0;
reg   [5:0] PL_Data;
reg   [31:0] internal_lin_counter;
reg    lin_addr_blk_n_AR;
wire    ap_CS_fsm_state3;
reg    lin_addr_blk_n_R;
wire    ap_CS_fsm_state10;
reg    lin_addr_blk_n_AW;
wire    ap_CS_fsm_state18;
reg    lin_addr_blk_n_W;
wire    ap_CS_fsm_state19;
reg    lin_addr_blk_n_B;
wire    ap_CS_fsm_state24;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state23;
wire    ap_CS_fsm_state26;
wire    ap_CS_fsm_state27;
wire    ap_CS_fsm_state32;
reg   [29:0] reg_459;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state25;
wire   [0:0] icmp_ln164_fu_585_p2;
wire   [0:0] icmp_ln167_fu_600_p2;
wire   [7:0] EN_cast_fu_463_p1;
reg   [7:0] EN_cast_reg_790;
reg   [29:0] trunc_ln_reg_798;
wire    ap_CS_fsm_state2;
wire   [0:0] exitcond181_fu_475_p2;
reg   [31:0] lin_addr_addr_reg_803;
reg   [3:0] PLIN_Ctrl_run_state_addr_reg_810;
wire    ap_CS_fsm_state9;
reg   [0:0] PLIN_Ctrl_run_state_load_reg_815;
reg   [31:0] lin_addr_addr_read_reg_819;
wire   [0:0] trunc_ln140_fu_526_p1;
reg   [29:0] trunc_ln81_2_reg_830;
reg   [0:0] icmp_ln164_reg_847;
reg   [0:0] icmp_ln167_reg_851;
reg   [3:0] lshr_ln_reg_855;
reg   [29:0] trunc_ln81_4_reg_867;
wire    ap_CS_fsm_state30;
wire   [4:0] zext_ln176_fu_652_p1;
reg   [4:0] zext_ln176_reg_872;
wire    ap_CS_fsm_state33;
wire   [4:0] add_ln176_fu_655_p2;
reg   [4:0] add_ln176_reg_877;
reg   [7:0] trunc_ln6_reg_882;
wire    ap_CS_fsm_state35;
reg   [7:0] trunc_ln7_reg_887;
reg   [7:0] trunc_ln8_reg_892;
reg   [7:0] trunc_ln9_reg_897;
reg   [7:0] trunc_ln1_reg_902;
wire   [7:0] trunc_ln189_fu_727_p1;
reg   [7:0] trunc_ln189_reg_907;
reg   [4:0] lin_frame_address0;
reg    lin_frame_ce0;
reg    lin_frame_we0;
reg   [7:0] lin_frame_d0;
wire   [7:0] lin_frame_q0;
reg   [4:0] lin_frame_address1;
reg    lin_frame_ce1;
reg    lin_frame_we1;
reg   [7:0] lin_frame_d1;
wire    grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_ap_start;
wire    grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_ap_done;
wire    grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_ap_idle;
wire    grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_ap_ready;
wire    grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_AWVALID;
wire   [31:0] grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_AWADDR;
wire   [0:0] grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_AWID;
wire   [31:0] grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_AWLEN;
wire   [2:0] grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_AWSIZE;
wire   [1:0] grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_AWBURST;
wire   [1:0] grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_AWLOCK;
wire   [3:0] grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_AWCACHE;
wire   [2:0] grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_AWPROT;
wire   [3:0] grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_AWQOS;
wire   [3:0] grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_AWREGION;
wire   [0:0] grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_AWUSER;
wire    grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_WVALID;
wire   [31:0] grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_WDATA;
wire   [3:0] grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_WSTRB;
wire    grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_WLAST;
wire   [0:0] grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_WID;
wire   [0:0] grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_WUSER;
wire    grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_ARVALID;
wire   [31:0] grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_ARADDR;
wire   [0:0] grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_ARID;
wire   [31:0] grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_ARLEN;
wire   [2:0] grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_ARSIZE;
wire   [1:0] grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_ARBURST;
wire   [1:0] grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_ARLOCK;
wire   [3:0] grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_ARCACHE;
wire   [2:0] grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_ARPROT;
wire   [3:0] grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_ARQOS;
wire   [3:0] grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_ARREGION;
wire   [0:0] grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_ARUSER;
wire    grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_RREADY;
wire    grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_BREADY;
wire   [4:0] grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_lin_frame_address0;
wire    grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_lin_frame_ce0;
wire    grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_lin_frame_we0;
wire   [7:0] grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_lin_frame_d0;
wire    grp_write_lin_ddr_1_fu_434_ap_start;
wire    grp_write_lin_ddr_1_fu_434_ap_done;
wire    grp_write_lin_ddr_1_fu_434_ap_idle;
wire    grp_write_lin_ddr_1_fu_434_ap_ready;
wire    grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_AWVALID;
wire   [31:0] grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_AWADDR;
wire   [0:0] grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_AWID;
wire   [31:0] grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_AWLEN;
wire   [2:0] grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_AWSIZE;
wire   [1:0] grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_AWBURST;
wire   [1:0] grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_AWLOCK;
wire   [3:0] grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_AWCACHE;
wire   [2:0] grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_AWPROT;
wire   [3:0] grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_AWQOS;
wire   [3:0] grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_AWREGION;
wire   [0:0] grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_AWUSER;
wire    grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_WVALID;
wire   [7:0] grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_WDATA;
wire   [0:0] grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_WSTRB;
wire    grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_WLAST;
wire   [0:0] grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_WID;
wire   [0:0] grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_WUSER;
wire    grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_ARVALID;
wire   [31:0] grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_ARADDR;
wire   [0:0] grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_ARID;
wire   [31:0] grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_ARLEN;
wire   [2:0] grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_ARSIZE;
wire   [1:0] grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_ARBURST;
wire   [1:0] grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_ARLOCK;
wire   [3:0] grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_ARCACHE;
wire   [2:0] grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_ARPROT;
wire   [3:0] grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_ARQOS;
wire   [3:0] grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_ARREGION;
wire   [0:0] grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_ARUSER;
wire    grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_RREADY;
wire    grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_BREADY;
wire   [4:0] grp_write_lin_ddr_1_fu_434_data_address0;
wire    grp_write_lin_ddr_1_fu_434_data_ce0;
reg    grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_ap_start_reg;
wire    ap_CS_fsm_state34;
reg    grp_write_lin_ddr_1_fu_434_ap_start_reg;
wire    ap_CS_fsm_state43;
wire    ap_CS_fsm_state44;
reg    ap_predicate_op193_call_state44;
reg    ap_block_state44_on_subcall_done;
wire   [31:0] p_cast_fu_487_p1;
wire   [31:0] zext_ln140_fu_522_p1;
wire    ap_CS_fsm_state36;
wire    ap_CS_fsm_state37;
wire    ap_CS_fsm_state38;
wire    ap_CS_fsm_state39;
wire    ap_CS_fsm_state40;
wire    ap_CS_fsm_state41;
wire    ap_CS_fsm_state42;
wire  signed [31:0] sext_ln81_fu_512_p1;
wire  signed [31:0] sext_ln81_1_fu_545_p1;
wire  signed [31:0] sext_ln87_fu_555_p1;
wire  signed [31:0] sext_ln87_1_fu_632_p1;
reg    ap_block_state18_io;
wire   [5:0] reg_lid_fu_566_p1;
wire   [31:0] add_ln200_fu_619_p2;
reg   [4:0] empty_fu_156;
wire   [4:0] empty_66_fu_481_p2;
wire   [7:0] zext_ln193_fu_735_p1;
wire   [7:0] zext_ln196_fu_744_p1;
wire   [7:0] zext_ln172_fu_749_p1;
wire   [31:0] grp_fu_444_p2;
wire   [31:0] add_ln81_fu_497_p2;
wire   [31:0] add_ln81_1_fu_530_p2;
wire   [2:0] tmp_fu_576_p4;
wire   [1:0] tmp_1_fu_591_p4;
wire   [4:0] add_ln193_fu_730_p2;
reg   [43:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
reg    ap_ST_fsm_state17_blk;
reg    ap_ST_fsm_state18_blk;
reg    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
reg    ap_ST_fsm_state23_blk;
reg    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
reg    ap_ST_fsm_state26_blk;
reg    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
reg    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
reg    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
wire    ap_ST_fsm_state42_blk;
wire    ap_ST_fsm_state43_blk;
reg    ap_ST_fsm_state44_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 44'd1;
#0 PL_Data = 6'd0;
#0 internal_lin_counter = 32'd0;
#0 grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_ap_start_reg = 1'b0;
#0 grp_write_lin_ddr_1_fu_434_ap_start_reg = 1'b0;
end

clu_single_lin_process_1_PLIN_Ctrl_run_state_RAM_AUTO_1R1W #(
    .DataWidth( 1 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
PLIN_Ctrl_run_state_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(PLIN_Ctrl_run_state_address0),
    .ce0(PLIN_Ctrl_run_state_ce0),
    .we0(PLIN_Ctrl_run_state_we0),
    .d0(PLIN_Ctrl_run_state_d0),
    .q0(PLIN_Ctrl_run_state_q0)
);

clu_single_lin_process_1_lin_frame_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 28 ),
    .AddressWidth( 5 ))
lin_frame_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(lin_frame_address0),
    .ce0(lin_frame_ce0),
    .we0(lin_frame_we0),
    .d0(lin_frame_d0),
    .q0(lin_frame_q0),
    .address1(lin_frame_address1),
    .ce1(lin_frame_ce1),
    .we1(lin_frame_we1),
    .d1(lin_frame_d1)
);

clu_single_lin_process_1_Pipeline_VITIS_LOOP_176_1 grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_ap_start),
    .ap_done(grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_ap_done),
    .ap_idle(grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_ap_idle),
    .ap_ready(grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_ap_ready),
    .m_axi_lin_addr_AWVALID(grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_AWVALID),
    .m_axi_lin_addr_AWREADY(1'b0),
    .m_axi_lin_addr_AWADDR(grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_AWADDR),
    .m_axi_lin_addr_AWID(grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_AWID),
    .m_axi_lin_addr_AWLEN(grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_AWLEN),
    .m_axi_lin_addr_AWSIZE(grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_AWSIZE),
    .m_axi_lin_addr_AWBURST(grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_AWBURST),
    .m_axi_lin_addr_AWLOCK(grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_AWLOCK),
    .m_axi_lin_addr_AWCACHE(grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_AWCACHE),
    .m_axi_lin_addr_AWPROT(grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_AWPROT),
    .m_axi_lin_addr_AWQOS(grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_AWQOS),
    .m_axi_lin_addr_AWREGION(grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_AWREGION),
    .m_axi_lin_addr_AWUSER(grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_AWUSER),
    .m_axi_lin_addr_WVALID(grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_WVALID),
    .m_axi_lin_addr_WREADY(1'b0),
    .m_axi_lin_addr_WDATA(grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_WDATA),
    .m_axi_lin_addr_WSTRB(grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_WSTRB),
    .m_axi_lin_addr_WLAST(grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_WLAST),
    .m_axi_lin_addr_WID(grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_WID),
    .m_axi_lin_addr_WUSER(grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_WUSER),
    .m_axi_lin_addr_ARVALID(grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_ARVALID),
    .m_axi_lin_addr_ARREADY(m_axi_lin_addr_ARREADY),
    .m_axi_lin_addr_ARADDR(grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_ARADDR),
    .m_axi_lin_addr_ARID(grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_ARID),
    .m_axi_lin_addr_ARLEN(grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_ARLEN),
    .m_axi_lin_addr_ARSIZE(grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_ARSIZE),
    .m_axi_lin_addr_ARBURST(grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_ARBURST),
    .m_axi_lin_addr_ARLOCK(grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_ARLOCK),
    .m_axi_lin_addr_ARCACHE(grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_ARCACHE),
    .m_axi_lin_addr_ARPROT(grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_ARPROT),
    .m_axi_lin_addr_ARQOS(grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_ARQOS),
    .m_axi_lin_addr_ARREGION(grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_ARREGION),
    .m_axi_lin_addr_ARUSER(grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_ARUSER),
    .m_axi_lin_addr_RVALID(m_axi_lin_addr_RVALID),
    .m_axi_lin_addr_RREADY(grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_RREADY),
    .m_axi_lin_addr_RDATA(m_axi_lin_addr_RDATA),
    .m_axi_lin_addr_RLAST(m_axi_lin_addr_RLAST),
    .m_axi_lin_addr_RID(m_axi_lin_addr_RID),
    .m_axi_lin_addr_RFIFONUM(m_axi_lin_addr_RFIFONUM),
    .m_axi_lin_addr_RUSER(m_axi_lin_addr_RUSER),
    .m_axi_lin_addr_RRESP(m_axi_lin_addr_RRESP),
    .m_axi_lin_addr_BVALID(1'b0),
    .m_axi_lin_addr_BREADY(grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_BREADY),
    .m_axi_lin_addr_BRESP(2'd0),
    .m_axi_lin_addr_BID(1'd0),
    .m_axi_lin_addr_BUSER(1'd0),
    .sext_ln81_2(trunc_ln81_4_reg_867),
    .add_ln176(add_ln176_reg_877),
    .lin_frame_address0(grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_lin_frame_address0),
    .lin_frame_ce0(grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_lin_frame_ce0),
    .lin_frame_we0(grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_lin_frame_we0),
    .lin_frame_d0(grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_lin_frame_d0)
);

clu_write_lin_ddr_1 grp_write_lin_ddr_1_fu_434(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_write_lin_ddr_1_fu_434_ap_start),
    .ap_done(grp_write_lin_ddr_1_fu_434_ap_done),
    .ap_idle(grp_write_lin_ddr_1_fu_434_ap_idle),
    .ap_ready(grp_write_lin_ddr_1_fu_434_ap_ready),
    .m_axi_ps_ddr_AWVALID(grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_AWVALID),
    .m_axi_ps_ddr_AWREADY(m_axi_ps_ddr_AWREADY),
    .m_axi_ps_ddr_AWADDR(grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_AWADDR),
    .m_axi_ps_ddr_AWID(grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_AWID),
    .m_axi_ps_ddr_AWLEN(grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_AWLEN),
    .m_axi_ps_ddr_AWSIZE(grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_AWSIZE),
    .m_axi_ps_ddr_AWBURST(grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_AWBURST),
    .m_axi_ps_ddr_AWLOCK(grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_AWLOCK),
    .m_axi_ps_ddr_AWCACHE(grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_AWCACHE),
    .m_axi_ps_ddr_AWPROT(grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_AWPROT),
    .m_axi_ps_ddr_AWQOS(grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_AWQOS),
    .m_axi_ps_ddr_AWREGION(grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_AWREGION),
    .m_axi_ps_ddr_AWUSER(grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_AWUSER),
    .m_axi_ps_ddr_WVALID(grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_WVALID),
    .m_axi_ps_ddr_WREADY(m_axi_ps_ddr_WREADY),
    .m_axi_ps_ddr_WDATA(grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_WDATA),
    .m_axi_ps_ddr_WSTRB(grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_WSTRB),
    .m_axi_ps_ddr_WLAST(grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_WLAST),
    .m_axi_ps_ddr_WID(grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_WID),
    .m_axi_ps_ddr_WUSER(grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_WUSER),
    .m_axi_ps_ddr_ARVALID(grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_ARVALID),
    .m_axi_ps_ddr_ARREADY(m_axi_ps_ddr_ARREADY),
    .m_axi_ps_ddr_ARADDR(grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_ARADDR),
    .m_axi_ps_ddr_ARID(grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_ARID),
    .m_axi_ps_ddr_ARLEN(grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_ARLEN),
    .m_axi_ps_ddr_ARSIZE(grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_ARSIZE),
    .m_axi_ps_ddr_ARBURST(grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_ARBURST),
    .m_axi_ps_ddr_ARLOCK(grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_ARLOCK),
    .m_axi_ps_ddr_ARCACHE(grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_ARCACHE),
    .m_axi_ps_ddr_ARPROT(grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_ARPROT),
    .m_axi_ps_ddr_ARQOS(grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_ARQOS),
    .m_axi_ps_ddr_ARREGION(grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_ARREGION),
    .m_axi_ps_ddr_ARUSER(grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_ARUSER),
    .m_axi_ps_ddr_RVALID(m_axi_ps_ddr_RVALID),
    .m_axi_ps_ddr_RREADY(grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_RREADY),
    .m_axi_ps_ddr_RDATA(m_axi_ps_ddr_RDATA),
    .m_axi_ps_ddr_RLAST(m_axi_ps_ddr_RLAST),
    .m_axi_ps_ddr_RID(m_axi_ps_ddr_RID),
    .m_axi_ps_ddr_RFIFONUM(m_axi_ps_ddr_RFIFONUM),
    .m_axi_ps_ddr_RUSER(m_axi_ps_ddr_RUSER),
    .m_axi_ps_ddr_RRESP(m_axi_ps_ddr_RRESP),
    .m_axi_ps_ddr_BVALID(m_axi_ps_ddr_BVALID),
    .m_axi_ps_ddr_BREADY(grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_BREADY),
    .m_axi_ps_ddr_BRESP(m_axi_ps_ddr_BRESP),
    .m_axi_ps_ddr_BID(m_axi_ps_ddr_BID),
    .m_axi_ps_ddr_BUSER(m_axi_ps_ddr_BUSER),
    .ddr_header(ddr),
    .data_address0(grp_write_lin_ddr_1_fu_434_data_address0),
    .data_ce0(grp_write_lin_ddr_1_fu_434_data_ce0),
    .data_q0(lin_frame_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state33)) begin
            grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_ap_start_reg <= 1'b1;
        end else if ((grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_ap_ready == 1'b1)) begin
            grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_write_lin_ddr_1_fu_434_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state43)) begin
            grp_write_lin_ddr_1_fu_434_ap_start_reg <= 1'b1;
        end else if ((grp_write_lin_ddr_1_fu_434_ap_ready == 1'b1)) begin
            grp_write_lin_ddr_1_fu_434_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        empty_fu_156 <= 5'd0;
    end else if (((exitcond181_fu_475_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        empty_fu_156 <= empty_66_fu_481_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        EN_cast_reg_790[3 : 0] <= EN_cast_fu_463_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        PLIN_Ctrl_run_state_addr_reg_810 <= zext_ln140_fu_522_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        PLIN_Ctrl_run_state_load_reg_815 <= PLIN_Ctrl_run_state_q0;
        lin_addr_addr_read_reg_819 <= m_axi_lin_addr_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state18_io) | (m_axi_lin_addr_RVALID == 1'b0)) & (1'b1 == ap_CS_fsm_state18))) begin
        PL_Data <= reg_lid_fu_566_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state33)) begin
        add_ln176_reg_877 <= add_ln176_fu_655_p2;
        zext_ln176_reg_872[3 : 0] <= zext_ln176_fu_652_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        icmp_ln164_reg_847 <= icmp_ln164_fu_585_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln164_fu_585_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state25))) begin
        icmp_ln167_reg_851 <= icmp_ln167_fu_600_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln167_fu_600_p2 == 1'd1) & (icmp_ln164_fu_585_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state25))) begin
        internal_lin_counter <= add_ln200_fu_619_p2;
        lshr_ln_reg_855 <= {{lin_addr_addr_read_reg_819[7:4]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        lin_addr_addr_reg_803 <= sext_ln81_fu_512_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state16) | ((icmp_ln167_fu_600_p2 == 1'd1) & (icmp_ln164_fu_585_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state25)))) begin
        reg_459 <= {{grp_fu_444_p2[31:2]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state35)) begin
        trunc_ln189_reg_907 <= trunc_ln189_fu_727_p1;
        trunc_ln1_reg_902 <= {{timestamp[15:8]}};
        trunc_ln6_reg_882 <= {{timestamp[47:40]}};
        trunc_ln7_reg_887 <= {{timestamp[39:32]}};
        trunc_ln8_reg_892 <= {{timestamp[31:24]}};
        trunc_ln9_reg_897 <= {{timestamp[23:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln140_fu_526_p1 == 1'd1) & (1'd0 == PLIN_Ctrl_run_state_q0) & (1'b1 == ap_CS_fsm_state10))) begin
        trunc_ln81_2_reg_830 <= {{add_ln81_1_fu_530_p2[31:2]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        trunc_ln81_4_reg_867 <= {{linbase[31:2]}};
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond181_fu_475_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        trunc_ln_reg_798 <= {{add_ln81_fu_497_p2[31:2]}};
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state11))) begin
        PLIN_Ctrl_run_state_address0 = PLIN_Ctrl_run_state_addr_reg_810;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        PLIN_Ctrl_run_state_address0 = zext_ln140_fu_522_p1;
    end else begin
        PLIN_Ctrl_run_state_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state25) | ((m_axi_lin_addr_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state11)))) begin
        PLIN_Ctrl_run_state_ce0 = 1'b1;
    end else begin
        PLIN_Ctrl_run_state_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        PLIN_Ctrl_run_state_d0 = 1'd0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        PLIN_Ctrl_run_state_d0 = 1'd1;
    end else begin
        PLIN_Ctrl_run_state_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((m_axi_lin_addr_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state11)) | ((icmp_ln167_fu_600_p2 == 1'd1) & (icmp_ln164_fu_585_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state25)))) begin
        PLIN_Ctrl_run_state_we0 = 1'b1;
    end else begin
        PLIN_Ctrl_run_state_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((m_axi_lin_addr_RVALID == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

always @ (*) begin
    if ((m_axi_lin_addr_ARREADY == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

always @ (*) begin
    if ((m_axi_lin_addr_AWREADY == 1'b0)) begin
        ap_ST_fsm_state17_blk = 1'b1;
    end else begin
        ap_ST_fsm_state17_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state18_io) | (m_axi_lin_addr_RVALID == 1'b0))) begin
        ap_ST_fsm_state18_blk = 1'b1;
    end else begin
        ap_ST_fsm_state18_blk = 1'b0;
    end
end

always @ (*) begin
    if ((m_axi_lin_addr_WREADY == 1'b0)) begin
        ap_ST_fsm_state19_blk = 1'b1;
    end else begin
        ap_ST_fsm_state19_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

always @ (*) begin
    if ((m_axi_lin_addr_BVALID == 1'b0)) begin
        ap_ST_fsm_state23_blk = 1'b1;
    end else begin
        ap_ST_fsm_state23_blk = 1'b0;
    end
end

always @ (*) begin
    if ((m_axi_lin_addr_BVALID == 1'b0)) begin
        ap_ST_fsm_state24_blk = 1'b1;
    end else begin
        ap_ST_fsm_state24_blk = 1'b0;
    end
end

assign ap_ST_fsm_state25_blk = 1'b0;

always @ (*) begin
    if ((m_axi_lin_addr_AWREADY == 1'b0)) begin
        ap_ST_fsm_state26_blk = 1'b1;
    end else begin
        ap_ST_fsm_state26_blk = 1'b0;
    end
end

always @ (*) begin
    if ((m_axi_lin_addr_WREADY == 1'b0)) begin
        ap_ST_fsm_state27_blk = 1'b1;
    end else begin
        ap_ST_fsm_state27_blk = 1'b0;
    end
end

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

always @ (*) begin
    if ((m_axi_lin_addr_BVALID == 1'b0)) begin
        ap_ST_fsm_state32_blk = 1'b1;
    end else begin
        ap_ST_fsm_state32_blk = 1'b0;
    end
end

assign ap_ST_fsm_state33_blk = 1'b0;

always @ (*) begin
    if ((grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_ap_done == 1'b0)) begin
        ap_ST_fsm_state34_blk = 1'b1;
    end else begin
        ap_ST_fsm_state34_blk = 1'b0;
    end
end

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

always @ (*) begin
    if ((m_axi_lin_addr_ARREADY == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state40_blk = 1'b0;

assign ap_ST_fsm_state41_blk = 1'b0;

assign ap_ST_fsm_state42_blk = 1'b0;

assign ap_ST_fsm_state43_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state44_on_subcall_done)) begin
        ap_ST_fsm_state44_blk = 1'b1;
    end else begin
        ap_ST_fsm_state44_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((1'b0 == ap_block_state44_on_subcall_done) & (1'b1 == ap_CS_fsm_state44)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state44_on_subcall_done) & (1'b1 == ap_CS_fsm_state44))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state3))) begin
        lin_addr_blk_n_AR = m_axi_lin_addr_ARREADY;
    end else begin
        lin_addr_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state18))) begin
        lin_addr_blk_n_AW = m_axi_lin_addr_AWREADY;
    end else begin
        lin_addr_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state24))) begin
        lin_addr_blk_n_B = m_axi_lin_addr_BVALID;
    end else begin
        lin_addr_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state10))) begin
        lin_addr_blk_n_R = m_axi_lin_addr_RVALID;
    end else begin
        lin_addr_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18))) begin
        lin_addr_blk_n_W = m_axi_lin_addr_WREADY;
    end else begin
        lin_addr_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state42)) begin
        lin_frame_address0 = 32'd14;
    end else if ((1'b1 == ap_CS_fsm_state41)) begin
        lin_frame_address0 = 32'd12;
    end else if ((1'b1 == ap_CS_fsm_state40)) begin
        lin_frame_address0 = 32'd10;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        lin_frame_address0 = 32'd8;
    end else if ((1'b1 == ap_CS_fsm_state38)) begin
        lin_frame_address0 = 32'd6;
    end else if ((1'b1 == ap_CS_fsm_state37)) begin
        lin_frame_address0 = 32'd4;
    end else if ((1'b1 == ap_CS_fsm_state36)) begin
        lin_frame_address0 = 32'd2;
    end else if ((1'b1 == ap_CS_fsm_state35)) begin
        lin_frame_address0 = 32'd1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        lin_frame_address0 = p_cast_fu_487_p1;
    end else if (((icmp_ln167_reg_851 == 1'd1) & (icmp_ln164_reg_847 == 1'd0) & (1'd1 == PLIN_Ctrl_run_state_load_reg_815) & (1'b1 == ap_CS_fsm_state44))) begin
        lin_frame_address0 = grp_write_lin_ddr_1_fu_434_data_address0;
    end else if ((1'b1 == ap_CS_fsm_state34)) begin
        lin_frame_address0 = grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_lin_frame_address0;
    end else begin
        lin_frame_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state42)) begin
        lin_frame_address1 = 32'd15;
    end else if ((1'b1 == ap_CS_fsm_state41)) begin
        lin_frame_address1 = 32'd13;
    end else if ((1'b1 == ap_CS_fsm_state40)) begin
        lin_frame_address1 = 32'd11;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        lin_frame_address1 = 32'd9;
    end else if ((1'b1 == ap_CS_fsm_state38)) begin
        lin_frame_address1 = 32'd7;
    end else if ((1'b1 == ap_CS_fsm_state37)) begin
        lin_frame_address1 = 32'd5;
    end else if ((1'b1 == ap_CS_fsm_state36)) begin
        lin_frame_address1 = 32'd3;
    end else if ((1'b1 == ap_CS_fsm_state35)) begin
        lin_frame_address1 = 32'd0;
    end else begin
        lin_frame_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state42) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state2))) begin
        lin_frame_ce0 = 1'b1;
    end else if (((icmp_ln167_reg_851 == 1'd1) & (icmp_ln164_reg_847 == 1'd0) & (1'd1 == PLIN_Ctrl_run_state_load_reg_815) & (1'b1 == ap_CS_fsm_state44))) begin
        lin_frame_ce0 = grp_write_lin_ddr_1_fu_434_data_ce0;
    end else if ((1'b1 == ap_CS_fsm_state34)) begin
        lin_frame_ce0 = grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_lin_frame_ce0;
    end else begin
        lin_frame_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state42) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state35))) begin
        lin_frame_ce1 = 1'b1;
    end else begin
        lin_frame_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state39)) begin
        lin_frame_d0 = 8'd3;
    end else if ((1'b1 == ap_CS_fsm_state38)) begin
        lin_frame_d0 = trunc_ln1_reg_902;
    end else if ((1'b1 == ap_CS_fsm_state37)) begin
        lin_frame_d0 = trunc_ln8_reg_892;
    end else if ((1'b1 == ap_CS_fsm_state36)) begin
        lin_frame_d0 = trunc_ln6_reg_882;
    end else if ((1'b1 == ap_CS_fsm_state35)) begin
        lin_frame_d0 = {{timestamp[55:48]}};
    end else if (((1'b1 == ap_CS_fsm_state42) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state2))) begin
        lin_frame_d0 = 8'd0;
    end else if ((1'b1 == ap_CS_fsm_state34)) begin
        lin_frame_d0 = grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_lin_frame_d0;
    end else begin
        lin_frame_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state42)) begin
        lin_frame_d1 = zext_ln172_fu_749_p1;
    end else if ((1'b1 == ap_CS_fsm_state41)) begin
        lin_frame_d1 = zext_ln196_fu_744_p1;
    end else if ((1'b1 == ap_CS_fsm_state40)) begin
        lin_frame_d1 = zext_ln193_fu_735_p1;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        lin_frame_d1 = EN_cast_reg_790;
    end else if ((1'b1 == ap_CS_fsm_state38)) begin
        lin_frame_d1 = trunc_ln189_reg_907;
    end else if ((1'b1 == ap_CS_fsm_state37)) begin
        lin_frame_d1 = trunc_ln9_reg_897;
    end else if ((1'b1 == ap_CS_fsm_state36)) begin
        lin_frame_d1 = trunc_ln7_reg_887;
    end else if ((1'b1 == ap_CS_fsm_state35)) begin
        lin_frame_d1 = {{timestamp[63:56]}};
    end else begin
        lin_frame_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state42) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state35) | ((exitcond181_fu_475_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        lin_frame_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state34)) begin
        lin_frame_we0 = grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_lin_frame_we0;
    end else begin
        lin_frame_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state42) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state35))) begin
        lin_frame_we1 = 1'b1;
    end else begin
        lin_frame_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_lin_addr_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        m_axi_lin_addr_ARADDR = sext_ln81_1_fu_545_p1;
    end else if (((m_axi_lin_addr_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_lin_addr_ARADDR = sext_ln81_fu_512_p1;
    end else if (((1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33))) begin
        m_axi_lin_addr_ARADDR = grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_ARADDR;
    end else begin
        m_axi_lin_addr_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33))) begin
        m_axi_lin_addr_ARBURST = grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_ARBURST;
    end else begin
        m_axi_lin_addr_ARBURST = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33))) begin
        m_axi_lin_addr_ARCACHE = grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_ARCACHE;
    end else begin
        m_axi_lin_addr_ARCACHE = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33))) begin
        m_axi_lin_addr_ARID = grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_ARID;
    end else begin
        m_axi_lin_addr_ARID = 1'd0;
    end
end

always @ (*) begin
    if ((((m_axi_lin_addr_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state11)) | ((m_axi_lin_addr_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3)))) begin
        m_axi_lin_addr_ARLEN = 32'd1;
    end else if (((1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33))) begin
        m_axi_lin_addr_ARLEN = grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_ARLEN;
    end else begin
        m_axi_lin_addr_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33))) begin
        m_axi_lin_addr_ARLOCK = grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_ARLOCK;
    end else begin
        m_axi_lin_addr_ARLOCK = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33))) begin
        m_axi_lin_addr_ARPROT = grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_ARPROT;
    end else begin
        m_axi_lin_addr_ARPROT = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33))) begin
        m_axi_lin_addr_ARQOS = grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_ARQOS;
    end else begin
        m_axi_lin_addr_ARQOS = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33))) begin
        m_axi_lin_addr_ARREGION = grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_ARREGION;
    end else begin
        m_axi_lin_addr_ARREGION = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33))) begin
        m_axi_lin_addr_ARSIZE = grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_ARSIZE;
    end else begin
        m_axi_lin_addr_ARSIZE = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33))) begin
        m_axi_lin_addr_ARUSER = grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_ARUSER;
    end else begin
        m_axi_lin_addr_ARUSER = 1'd0;
    end
end

always @ (*) begin
    if ((((m_axi_lin_addr_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state11)) | ((m_axi_lin_addr_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3)))) begin
        m_axi_lin_addr_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33))) begin
        m_axi_lin_addr_ARVALID = grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_ARVALID;
    end else begin
        m_axi_lin_addr_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_lin_addr_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state26))) begin
        m_axi_lin_addr_AWADDR = sext_ln87_1_fu_632_p1;
    end else if (((m_axi_lin_addr_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
        m_axi_lin_addr_AWADDR = sext_ln87_fu_555_p1;
    end else if ((~((1'b1 == ap_block_state18_io) | (m_axi_lin_addr_RVALID == 1'b0)) & (1'b1 == ap_CS_fsm_state18))) begin
        m_axi_lin_addr_AWADDR = lin_addr_addr_reg_803;
    end else begin
        m_axi_lin_addr_AWADDR = 'bx;
    end
end

always @ (*) begin
    if ((((m_axi_lin_addr_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state26)) | ((m_axi_lin_addr_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state17)) | (~((1'b1 == ap_block_state18_io) | (m_axi_lin_addr_RVALID == 1'b0)) & (1'b1 == ap_CS_fsm_state18)))) begin
        m_axi_lin_addr_AWVALID = 1'b1;
    end else begin
        m_axi_lin_addr_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state32) & (m_axi_lin_addr_BVALID == 1'b1)) | ((1'b1 == ap_CS_fsm_state23) & (m_axi_lin_addr_BVALID == 1'b1)) | ((1'b1 == ap_CS_fsm_state24) & (m_axi_lin_addr_BVALID == 1'b1)))) begin
        m_axi_lin_addr_BREADY = 1'b1;
    end else begin
        m_axi_lin_addr_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_block_state18_io) | (m_axi_lin_addr_RVALID == 1'b0)) & (1'b1 == ap_CS_fsm_state18)) | ((1'b1 == ap_CS_fsm_state10) & (m_axi_lin_addr_RVALID == 1'b1)))) begin
        m_axi_lin_addr_RREADY = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33))) begin
        m_axi_lin_addr_RREADY = grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_m_axi_lin_addr_RREADY;
    end else begin
        m_axi_lin_addr_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        m_axi_lin_addr_WDATA = 32'd128;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        m_axi_lin_addr_WDATA = 32'd59;
    end else if (((1'b1 == ap_CS_fsm_state18) & (m_axi_lin_addr_RVALID == 1'b1))) begin
        m_axi_lin_addr_WDATA = 32'd0;
    end else begin
        m_axi_lin_addr_WDATA = 'bx;
    end
end

always @ (*) begin
    if ((((m_axi_lin_addr_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state27)) | ((m_axi_lin_addr_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state19)) | (~((1'b1 == ap_block_state18_io) | (m_axi_lin_addr_RVALID == 1'b0)) & (1'b1 == ap_CS_fsm_state18)))) begin
        m_axi_lin_addr_WVALID = 1'b1;
    end else begin
        m_axi_lin_addr_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state43) | ((icmp_ln167_reg_851 == 1'd1) & (icmp_ln164_reg_847 == 1'd0) & (1'd1 == PLIN_Ctrl_run_state_load_reg_815) & (1'b1 == ap_CS_fsm_state44)))) begin
        m_axi_ps_ddr_ARVALID = grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_ARVALID;
    end else begin
        m_axi_ps_ddr_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state43) | ((icmp_ln167_reg_851 == 1'd1) & (icmp_ln164_reg_847 == 1'd0) & (1'd1 == PLIN_Ctrl_run_state_load_reg_815) & (1'b1 == ap_CS_fsm_state44)))) begin
        m_axi_ps_ddr_AWVALID = grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_AWVALID;
    end else begin
        m_axi_ps_ddr_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state43) | ((icmp_ln167_reg_851 == 1'd1) & (icmp_ln164_reg_847 == 1'd0) & (1'd1 == PLIN_Ctrl_run_state_load_reg_815) & (1'b1 == ap_CS_fsm_state44)))) begin
        m_axi_ps_ddr_BREADY = grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_BREADY;
    end else begin
        m_axi_ps_ddr_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state43) | ((icmp_ln167_reg_851 == 1'd1) & (icmp_ln164_reg_847 == 1'd0) & (1'd1 == PLIN_Ctrl_run_state_load_reg_815) & (1'b1 == ap_CS_fsm_state44)))) begin
        m_axi_ps_ddr_RREADY = grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_RREADY;
    end else begin
        m_axi_ps_ddr_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state43) | ((icmp_ln167_reg_851 == 1'd1) & (icmp_ln164_reg_847 == 1'd0) & (1'd1 == PLIN_Ctrl_run_state_load_reg_815) & (1'b1 == ap_CS_fsm_state44)))) begin
        m_axi_ps_ddr_WVALID = grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_WVALID;
    end else begin
        m_axi_ps_ddr_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln167_fu_600_p2 == 1'd1) & (icmp_ln164_fu_585_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state25))) begin
        received_lin_ap_vld = 1'b1;
    end else begin
        received_lin_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((exitcond181_fu_475_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((m_axi_lin_addr_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((trunc_ln140_fu_526_p1 == 1'd0) & (1'd0 == PLIN_Ctrl_run_state_q0) & (1'b1 == ap_CS_fsm_state10) & (m_axi_lin_addr_RVALID == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state44;
            end else if (((trunc_ln140_fu_526_p1 == 1'd1) & (1'd0 == PLIN_Ctrl_run_state_q0) & (1'b1 == ap_CS_fsm_state10) & (m_axi_lin_addr_RVALID == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else if (((1'd1 == PLIN_Ctrl_run_state_q0) & (1'b1 == ap_CS_fsm_state10) & (m_axi_lin_addr_RVALID == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            if (((m_axi_lin_addr_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            if (((m_axi_lin_addr_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state18 : begin
            if ((~((1'b1 == ap_block_state18_io) | (m_axi_lin_addr_RVALID == 1'b0)) & (1'b1 == ap_CS_fsm_state18))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        ap_ST_fsm_state19 : begin
            if (((m_axi_lin_addr_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            if (((1'b1 == ap_CS_fsm_state23) & (m_axi_lin_addr_BVALID == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end
        end
        ap_ST_fsm_state24 : begin
            if (((1'b1 == ap_CS_fsm_state24) & (m_axi_lin_addr_BVALID == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state44;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end
        end
        ap_ST_fsm_state25 : begin
            if (((icmp_ln167_fu_600_p2 == 1'd1) & (icmp_ln164_fu_585_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state25))) begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state44;
            end
        end
        ap_ST_fsm_state26 : begin
            if (((m_axi_lin_addr_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state26))) begin
                ap_NS_fsm = ap_ST_fsm_state27;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end
        end
        ap_ST_fsm_state27 : begin
            if (((m_axi_lin_addr_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state27))) begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state27;
            end
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            if (((1'b1 == ap_CS_fsm_state32) & (m_axi_lin_addr_BVALID == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state33;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state32;
            end
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            if (((grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state34))) begin
                ap_NS_fsm = ap_ST_fsm_state35;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state34;
            end
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            if (((1'b0 == ap_block_state44_on_subcall_done) & (1'b1 == ap_CS_fsm_state44))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state44;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign EN_cast_fu_463_p1 = EN;

assign add_ln176_fu_655_p2 = (zext_ln176_fu_652_p1 + 5'd1);

assign add_ln193_fu_730_p2 = (zext_ln176_reg_872 + 5'd4);

assign add_ln200_fu_619_p2 = (internal_lin_counter + 32'd1);

assign add_ln81_1_fu_530_p2 = (linbase + 32'd8);

assign add_ln81_fu_497_p2 = (linbase + 32'd20);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd31];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_state34 = ap_CS_fsm[32'd33];

assign ap_CS_fsm_state35 = ap_CS_fsm[32'd34];

assign ap_CS_fsm_state36 = ap_CS_fsm[32'd35];

assign ap_CS_fsm_state37 = ap_CS_fsm[32'd36];

assign ap_CS_fsm_state38 = ap_CS_fsm[32'd37];

assign ap_CS_fsm_state39 = ap_CS_fsm[32'd38];

assign ap_CS_fsm_state40 = ap_CS_fsm[32'd39];

assign ap_CS_fsm_state41 = ap_CS_fsm[32'd40];

assign ap_CS_fsm_state42 = ap_CS_fsm[32'd41];

assign ap_CS_fsm_state43 = ap_CS_fsm[32'd42];

assign ap_CS_fsm_state44 = ap_CS_fsm[32'd43];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state18_io = ((m_axi_lin_addr_WREADY == 1'b0) | (m_axi_lin_addr_AWREADY == 1'b0));
end

always @ (*) begin
    ap_block_state44_on_subcall_done = ((ap_predicate_op193_call_state44 == 1'b1) & (grp_write_lin_ddr_1_fu_434_ap_done == 1'b0));
end

always @ (*) begin
    ap_predicate_op193_call_state44 = ((icmp_ln167_reg_851 == 1'd1) & (icmp_ln164_reg_847 == 1'd0) & (1'd1 == PLIN_Ctrl_run_state_load_reg_815));
end

assign empty_66_fu_481_p2 = (empty_fu_156 + 5'd1);

assign exitcond181_fu_475_p2 = ((empty_fu_156 == 5'd28) ? 1'b1 : 1'b0);

assign grp_fu_444_p2 = (linbase + 32'd4);

assign grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_ap_start = grp_single_lin_process_1_Pipeline_VITIS_LOOP_176_1_fu_425_ap_start_reg;

assign grp_write_lin_ddr_1_fu_434_ap_start = grp_write_lin_ddr_1_fu_434_ap_start_reg;

assign icmp_ln164_fu_585_p2 = ((tmp_fu_576_p4 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln167_fu_600_p2 = ((tmp_1_fu_591_p4 == 2'd0) ? 1'b1 : 1'b0);

assign m_axi_lin_addr_AWBURST = 2'd0;

assign m_axi_lin_addr_AWCACHE = 4'd0;

assign m_axi_lin_addr_AWID = 1'd0;

assign m_axi_lin_addr_AWLEN = 32'd1;

assign m_axi_lin_addr_AWLOCK = 2'd0;

assign m_axi_lin_addr_AWPROT = 3'd0;

assign m_axi_lin_addr_AWQOS = 4'd0;

assign m_axi_lin_addr_AWREGION = 4'd0;

assign m_axi_lin_addr_AWSIZE = 3'd0;

assign m_axi_lin_addr_AWUSER = 1'd0;

assign m_axi_lin_addr_WID = 1'd0;

assign m_axi_lin_addr_WLAST = 1'b0;

assign m_axi_lin_addr_WSTRB = 4'd15;

assign m_axi_lin_addr_WUSER = 1'd0;

assign m_axi_ps_ddr_ARADDR = grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_ARADDR;

assign m_axi_ps_ddr_ARBURST = grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_ARBURST;

assign m_axi_ps_ddr_ARCACHE = grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_ARCACHE;

assign m_axi_ps_ddr_ARID = grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_ARID;

assign m_axi_ps_ddr_ARLEN = grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_ARLEN;

assign m_axi_ps_ddr_ARLOCK = grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_ARLOCK;

assign m_axi_ps_ddr_ARPROT = grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_ARPROT;

assign m_axi_ps_ddr_ARQOS = grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_ARQOS;

assign m_axi_ps_ddr_ARREGION = grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_ARREGION;

assign m_axi_ps_ddr_ARSIZE = grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_ARSIZE;

assign m_axi_ps_ddr_ARUSER = grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_ARUSER;

assign m_axi_ps_ddr_AWADDR = grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_AWADDR;

assign m_axi_ps_ddr_AWBURST = grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_AWBURST;

assign m_axi_ps_ddr_AWCACHE = grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_AWCACHE;

assign m_axi_ps_ddr_AWID = grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_AWID;

assign m_axi_ps_ddr_AWLEN = grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_AWLEN;

assign m_axi_ps_ddr_AWLOCK = grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_AWLOCK;

assign m_axi_ps_ddr_AWPROT = grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_AWPROT;

assign m_axi_ps_ddr_AWQOS = grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_AWQOS;

assign m_axi_ps_ddr_AWREGION = grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_AWREGION;

assign m_axi_ps_ddr_AWSIZE = grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_AWSIZE;

assign m_axi_ps_ddr_AWUSER = grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_AWUSER;

assign m_axi_ps_ddr_WDATA = grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_WDATA;

assign m_axi_ps_ddr_WID = grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_WID;

assign m_axi_ps_ddr_WLAST = grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_WLAST;

assign m_axi_ps_ddr_WSTRB = grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_WSTRB;

assign m_axi_ps_ddr_WUSER = grp_write_lin_ddr_1_fu_434_m_axi_ps_ddr_WUSER;

assign p_cast_fu_487_p1 = empty_fu_156;

assign received_lin = (internal_lin_counter + 32'd1);

assign reg_lid_fu_566_p1 = m_axi_lin_addr_RDATA[5:0];

assign sext_ln81_1_fu_545_p1 = $signed(trunc_ln81_2_reg_830);

assign sext_ln81_fu_512_p1 = $signed(trunc_ln_reg_798);

assign sext_ln87_1_fu_632_p1 = $signed(reg_459);

assign sext_ln87_fu_555_p1 = $signed(reg_459);

assign tmp_1_fu_591_p4 = {{lin_addr_addr_read_reg_819[3:2]}};

assign tmp_fu_576_p4 = {{lin_addr_addr_read_reg_819[3:1]}};

assign trunc_ln140_fu_526_p1 = m_axi_lin_addr_RDATA[0:0];

assign trunc_ln189_fu_727_p1 = timestamp[7:0];

assign zext_ln140_fu_522_p1 = EN;

assign zext_ln172_fu_749_p1 = lshr_ln_reg_855;

assign zext_ln176_fu_652_p1 = lshr_ln_reg_855;

assign zext_ln193_fu_735_p1 = add_ln193_fu_730_p2;

assign zext_ln196_fu_744_p1 = PL_Data;

always @ (posedge ap_clk) begin
    EN_cast_reg_790[7:4] <= 4'b0000;
    zext_ln176_reg_872[4] <= 1'b0;
end

endmodule //clu_single_lin_process_1
