// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module clu_recvFrame_logic_1_Pipeline_VITIS_LOOP_205_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_can_addr_AWVALID,
        m_axi_can_addr_AWREADY,
        m_axi_can_addr_AWADDR,
        m_axi_can_addr_AWID,
        m_axi_can_addr_AWLEN,
        m_axi_can_addr_AWSIZE,
        m_axi_can_addr_AWBURST,
        m_axi_can_addr_AWLOCK,
        m_axi_can_addr_AWCACHE,
        m_axi_can_addr_AWPROT,
        m_axi_can_addr_AWQOS,
        m_axi_can_addr_AWREGION,
        m_axi_can_addr_AWUSER,
        m_axi_can_addr_WVALID,
        m_axi_can_addr_WREADY,
        m_axi_can_addr_WDATA,
        m_axi_can_addr_WSTRB,
        m_axi_can_addr_WLAST,
        m_axi_can_addr_WID,
        m_axi_can_addr_WUSER,
        m_axi_can_addr_ARVALID,
        m_axi_can_addr_ARREADY,
        m_axi_can_addr_ARADDR,
        m_axi_can_addr_ARID,
        m_axi_can_addr_ARLEN,
        m_axi_can_addr_ARSIZE,
        m_axi_can_addr_ARBURST,
        m_axi_can_addr_ARLOCK,
        m_axi_can_addr_ARCACHE,
        m_axi_can_addr_ARPROT,
        m_axi_can_addr_ARQOS,
        m_axi_can_addr_ARREGION,
        m_axi_can_addr_ARUSER,
        m_axi_can_addr_RVALID,
        m_axi_can_addr_RREADY,
        m_axi_can_addr_RDATA,
        m_axi_can_addr_RLAST,
        m_axi_can_addr_RID,
        m_axi_can_addr_RFIFONUM,
        m_axi_can_addr_RUSER,
        m_axi_can_addr_RRESP,
        m_axi_can_addr_BVALID,
        m_axi_can_addr_BREADY,
        m_axi_can_addr_BRESP,
        m_axi_can_addr_BID,
        m_axi_can_addr_BUSER,
        add_ln205_1,
        canbase,
        zext_ln205,
        can_frame_address0,
        can_frame_ce0,
        can_frame_we0,
        can_frame_d0,
        can_frame_address1,
        can_frame_ce1,
        can_frame_we1,
        can_frame_d1
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_can_addr_AWVALID;
input   m_axi_can_addr_AWREADY;
output  [31:0] m_axi_can_addr_AWADDR;
output  [0:0] m_axi_can_addr_AWID;
output  [31:0] m_axi_can_addr_AWLEN;
output  [2:0] m_axi_can_addr_AWSIZE;
output  [1:0] m_axi_can_addr_AWBURST;
output  [1:0] m_axi_can_addr_AWLOCK;
output  [3:0] m_axi_can_addr_AWCACHE;
output  [2:0] m_axi_can_addr_AWPROT;
output  [3:0] m_axi_can_addr_AWQOS;
output  [3:0] m_axi_can_addr_AWREGION;
output  [0:0] m_axi_can_addr_AWUSER;
output   m_axi_can_addr_WVALID;
input   m_axi_can_addr_WREADY;
output  [31:0] m_axi_can_addr_WDATA;
output  [3:0] m_axi_can_addr_WSTRB;
output   m_axi_can_addr_WLAST;
output  [0:0] m_axi_can_addr_WID;
output  [0:0] m_axi_can_addr_WUSER;
output   m_axi_can_addr_ARVALID;
input   m_axi_can_addr_ARREADY;
output  [31:0] m_axi_can_addr_ARADDR;
output  [0:0] m_axi_can_addr_ARID;
output  [31:0] m_axi_can_addr_ARLEN;
output  [2:0] m_axi_can_addr_ARSIZE;
output  [1:0] m_axi_can_addr_ARBURST;
output  [1:0] m_axi_can_addr_ARLOCK;
output  [3:0] m_axi_can_addr_ARCACHE;
output  [2:0] m_axi_can_addr_ARPROT;
output  [3:0] m_axi_can_addr_ARQOS;
output  [3:0] m_axi_can_addr_ARREGION;
output  [0:0] m_axi_can_addr_ARUSER;
input   m_axi_can_addr_RVALID;
output   m_axi_can_addr_RREADY;
input  [31:0] m_axi_can_addr_RDATA;
input   m_axi_can_addr_RLAST;
input  [0:0] m_axi_can_addr_RID;
input  [8:0] m_axi_can_addr_RFIFONUM;
input  [0:0] m_axi_can_addr_RUSER;
input  [1:0] m_axi_can_addr_RRESP;
input   m_axi_can_addr_BVALID;
output   m_axi_can_addr_BREADY;
input  [1:0] m_axi_can_addr_BRESP;
input  [0:0] m_axi_can_addr_BID;
input  [0:0] m_axi_can_addr_BUSER;
input  [4:0] add_ln205_1;
input  [31:0] canbase;
input  [14:0] zext_ln205;
output  [6:0] can_frame_address0;
output   can_frame_ce0;
output   can_frame_we0;
output  [7:0] can_frame_d0;
output  [6:0] can_frame_address1;
output   can_frame_ce1;
output   can_frame_we1;
output  [7:0] can_frame_d1;

reg ap_idle;
reg m_axi_can_addr_ARVALID;
reg m_axi_can_addr_RREADY;
reg[6:0] can_frame_address0;
reg can_frame_ce0;
reg can_frame_we0;
reg[7:0] can_frame_d0;
reg[6:0] can_frame_address1;
reg can_frame_ce1;
reg can_frame_we1;
reg[7:0] can_frame_d1;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
reg   [0:0] icmp_ln205_reg_355;
reg    ap_block_state2_io;
wire    ap_block_state4_pp0_stage1_iter1;
wire    ap_block_state6_pp0_stage1_iter2;
wire    ap_block_state8_pp0_stage1_iter3;
wire    ap_block_state10_pp0_stage1_iter4;
reg    ap_block_pp0_stage1_subdone;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    can_addr_blk_n_AR;
wire    ap_block_pp0_stage1;
reg    can_addr_blk_n_R;
wire    ap_block_pp0_stage0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state5_pp0_stage0_iter2;
wire    ap_block_state7_pp0_stage0_iter3;
reg    ap_block_state9_pp0_stage0_iter4;
wire    ap_block_state11_pp0_stage0_iter5;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln205_fu_186_p2;
reg   [0:0] icmp_ln205_reg_355_pp0_iter1_reg;
reg   [0:0] icmp_ln205_reg_355_pp0_iter2_reg;
reg   [0:0] icmp_ln205_reg_355_pp0_iter3_reg;
reg   [29:0] trunc_ln_reg_359;
reg    ap_block_pp0_stage1_11001;
reg   [7:0] trunc_ln5_reg_370;
reg   [7:0] trunc_ln6_reg_375;
reg   [7:0] trunc_ln7_reg_380;
wire   [7:0] trunc_ln212_fu_281_p1;
reg   [7:0] trunc_ln212_reg_385;
reg   [6:0] canIndex_load_reg_390;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_pp0_stage0_subdone;
wire   [31:0] zext_ln209_fu_294_p1;
wire   [31:0] zext_ln210_fu_305_p1;
wire   [31:0] zext_ln211_fu_326_p1;
wire   [31:0] zext_ln212_fu_336_p1;
wire  signed [31:0] sext_ln207_fu_241_p1;
reg   [4:0] DwIndex_fu_90;
wire   [4:0] DwIndex_2_fu_192_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_DwIndex_1;
reg   [6:0] canIndex_fu_94;
wire   [6:0] add_ln213_fu_310_p2;
wire   [3:0] trunc_ln208_fu_198_p1;
wire   [5:0] shl_ln3_fu_202_p3;
wire   [31:0] zext_ln207_fu_210_p1;
wire   [31:0] add_ln207_1_fu_214_p2;
wire   [31:0] zext_ln205_cast_fu_169_p1;
wire   [31:0] add_ln207_fu_220_p2;
wire   [6:0] add_ln209_fu_288_p2;
wire   [6:0] add_ln210_fu_299_p2;
wire   [6:0] add_ln211_fu_321_p2;
wire   [6:0] add_ln212_fu_331_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter4_stage0;
reg    ap_idle_pp0_0to3;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_1to5;
reg    ap_done_pending_pp0;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

clu_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter5 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln205_fu_186_p2 == 1'd0))) begin
            DwIndex_fu_90 <= DwIndex_2_fu_192_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            DwIndex_fu_90 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage0))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage0))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        canIndex_fu_94 <= 7'd8;
    end else if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        canIndex_fu_94 <= add_ln213_fu_310_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        canIndex_load_reg_390 <= canIndex_fu_94;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln205_reg_355 <= icmp_ln205_fu_186_p2;
        icmp_ln205_reg_355_pp0_iter1_reg <= icmp_ln205_reg_355;
        icmp_ln205_reg_355_pp0_iter2_reg <= icmp_ln205_reg_355_pp0_iter1_reg;
        icmp_ln205_reg_355_pp0_iter3_reg <= icmp_ln205_reg_355_pp0_iter2_reg;
        trunc_ln212_reg_385 <= trunc_ln212_fu_281_p1;
        trunc_ln5_reg_370 <= {{m_axi_can_addr_RDATA[31:24]}};
        trunc_ln6_reg_375 <= {{m_axi_can_addr_RDATA[23:16]}};
        trunc_ln7_reg_380 <= {{m_axi_can_addr_RDATA[15:8]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln205_fu_186_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        trunc_ln_reg_359 <= {{add_ln207_fu_220_p2[31:2]}};
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone) & (icmp_ln205_reg_355 == 1'd1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln205_reg_355_pp0_iter3_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter4_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter4_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (~((ap_loop_exit_ready_pp0_iter4_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b0) & (ap_loop_exit_ready == 1'b0))) begin
        ap_done_pending_pp0 = 1'b1;
    end else begin
        ap_done_pending_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to3 = 1'b1;
    end else begin
        ap_idle_pp0_0to3 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to5 = 1'b1;
    end else begin
        ap_idle_pp0_1to5 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_DwIndex_1 = 5'd0;
    end else begin
        ap_sig_allocacmp_DwIndex_1 = DwIndex_fu_90;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1) & (icmp_ln205_reg_355 == 1'd0))) begin
        can_addr_blk_n_AR = m_axi_can_addr_ARREADY;
    end else begin
        can_addr_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        can_addr_blk_n_R = m_axi_can_addr_RVALID;
    end else begin
        can_addr_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        can_frame_address0 = zext_ln212_fu_336_p1;
    end else if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        can_frame_address0 = zext_ln210_fu_305_p1;
    end else begin
        can_frame_address0 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        can_frame_address1 = zext_ln211_fu_326_p1;
    end else if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        can_frame_address1 = zext_ln209_fu_294_p1;
    end else begin
        can_frame_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)))) begin
        can_frame_ce0 = 1'b1;
    end else begin
        can_frame_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)))) begin
        can_frame_ce1 = 1'b1;
    end else begin
        can_frame_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        can_frame_d0 = trunc_ln212_reg_385;
    end else if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        can_frame_d0 = trunc_ln6_reg_375;
    end else begin
        can_frame_d0 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        can_frame_d1 = trunc_ln7_reg_380;
    end else if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        can_frame_d1 = trunc_ln5_reg_370;
    end else begin
        can_frame_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)))) begin
        can_frame_we0 = 1'b1;
    end else begin
        can_frame_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)))) begin
        can_frame_we1 = 1'b1;
    end else begin
        can_frame_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln205_reg_355 == 1'd0))) begin
        m_axi_can_addr_ARVALID = 1'b1;
    end else begin
        m_axi_can_addr_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_can_addr_RREADY = 1'b1;
    end else begin
        m_axi_can_addr_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_done_pending_pp0 == 1'b0) & (ap_idle_pp0_1to5 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign DwIndex_2_fu_192_p2 = (ap_sig_allocacmp_DwIndex_1 + 5'd1);

assign add_ln207_1_fu_214_p2 = (zext_ln207_fu_210_p1 + canbase);

assign add_ln207_fu_220_p2 = (add_ln207_1_fu_214_p2 + zext_ln205_cast_fu_169_p1);

assign add_ln209_fu_288_p2 = (canIndex_fu_94 + 7'd12);

assign add_ln210_fu_299_p2 = (canIndex_fu_94 + 7'd13);

assign add_ln211_fu_321_p2 = (canIndex_load_reg_390 + 7'd14);

assign add_ln212_fu_331_p2 = (canIndex_load_reg_390 + 7'd15);

assign add_ln213_fu_310_p2 = (canIndex_fu_94 + 7'd4);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((m_axi_can_addr_RVALID == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((m_axi_can_addr_RVALID == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state2_io));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state2_io));
end

assign ap_block_state10_pp0_stage1_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_io = ((m_axi_can_addr_ARREADY == 1'b0) & (icmp_ln205_reg_355 == 1'd0));
end

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage1_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state9_pp0_stage0_iter4 = (m_axi_can_addr_RVALID == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign icmp_ln205_fu_186_p2 = ((ap_sig_allocacmp_DwIndex_1 == add_ln205_1) ? 1'b1 : 1'b0);

assign m_axi_can_addr_ARADDR = sext_ln207_fu_241_p1;

assign m_axi_can_addr_ARBURST = 2'd0;

assign m_axi_can_addr_ARCACHE = 4'd0;

assign m_axi_can_addr_ARID = 1'd0;

assign m_axi_can_addr_ARLEN = 32'd1;

assign m_axi_can_addr_ARLOCK = 2'd0;

assign m_axi_can_addr_ARPROT = 3'd0;

assign m_axi_can_addr_ARQOS = 4'd0;

assign m_axi_can_addr_ARREGION = 4'd0;

assign m_axi_can_addr_ARSIZE = 3'd0;

assign m_axi_can_addr_ARUSER = 1'd0;

assign m_axi_can_addr_AWADDR = 32'd0;

assign m_axi_can_addr_AWBURST = 2'd0;

assign m_axi_can_addr_AWCACHE = 4'd0;

assign m_axi_can_addr_AWID = 1'd0;

assign m_axi_can_addr_AWLEN = 32'd0;

assign m_axi_can_addr_AWLOCK = 2'd0;

assign m_axi_can_addr_AWPROT = 3'd0;

assign m_axi_can_addr_AWQOS = 4'd0;

assign m_axi_can_addr_AWREGION = 4'd0;

assign m_axi_can_addr_AWSIZE = 3'd0;

assign m_axi_can_addr_AWUSER = 1'd0;

assign m_axi_can_addr_AWVALID = 1'b0;

assign m_axi_can_addr_BREADY = 1'b0;

assign m_axi_can_addr_WDATA = 32'd0;

assign m_axi_can_addr_WID = 1'd0;

assign m_axi_can_addr_WLAST = 1'b0;

assign m_axi_can_addr_WSTRB = 4'd0;

assign m_axi_can_addr_WUSER = 1'd0;

assign m_axi_can_addr_WVALID = 1'b0;

assign sext_ln207_fu_241_p1 = $signed(trunc_ln_reg_359);

assign shl_ln3_fu_202_p3 = {{trunc_ln208_fu_198_p1}, {2'd0}};

assign trunc_ln208_fu_198_p1 = ap_sig_allocacmp_DwIndex_1[3:0];

assign trunc_ln212_fu_281_p1 = m_axi_can_addr_RDATA[7:0];

assign zext_ln205_cast_fu_169_p1 = zext_ln205;

assign zext_ln207_fu_210_p1 = shl_ln3_fu_202_p3;

assign zext_ln209_fu_294_p1 = add_ln209_fu_288_p2;

assign zext_ln210_fu_305_p1 = add_ln210_fu_299_p2;

assign zext_ln211_fu_326_p1 = add_ln211_fu_321_p2;

assign zext_ln212_fu_336_p1 = add_ln212_fu_331_p2;

endmodule //clu_recvFrame_logic_1_Pipeline_VITIS_LOOP_205_1
