
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2022 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xtimestamp.h"

/*
* The configuration table for devices
*/

XTimestamp_Config XTimestamp_ConfigTable[XPAR_XTIMESTAMP_NUM_INSTANCES] =
{
	{
		XPAR_TIMESTAMP_0_DEVICE_ID,
		XPAR_TIMESTAMP_0_S_AXI_TS_BASE_BASEADDR
	}
};


